config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'
  resources :users, only: [:show, :index, :new, :create]
  resource :sessions, only:[:new, :create, :destroy]
  resources :questions do
    resources :comments, except: [:show] do
    end
  end

  resources :questions do
    resources :answers
  end
  resources :answers, except: [:show] do
    resources :comments, except: [:show, :index] do
    end
  end

  resources :tags, only: [:show, :index]
  resources :questions, only:[] do
    resources :votes, only:[:create]
  end
  resources :answers, only:[] do
    resources :votes, only:[:create]
  end
  post '/tags/search' => 'tags#search'
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'

end

app/models/question.rb
class Question < ActiveRecord::Base
	include Createable
	include VoteCounter

  has_many :answers, dependent: :destroy

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy

  belongs_to :user
  has_and_belongs_to_many :tags


  validates :title, :body, presence:true
  validates :title, length: {in: 1..400}
  validates :body, length: {in: 1..3000}

  def self.added_today
    where("created_at >= ?", Time.zone.now.beginning_of_day)
  end

  def self.added_this_week
    where("created_at >= ?", Time.zone.now.beginning_of_day - 7.days)
  end

  def self.latest
    #You don't need the all here
    Question.order(updated_at: :desc)
  end

  #Maybe call this most_voted or highest_voted
  def self.greatest
    # Question.joins(:votes).group('questions.id').order('sum(case when votes.up_vote then 1 else -1 end) desc').limit(10)
    questions = Question.all
    questions.sort_by{|question| -question.vote_count}
  end

  # You can do this in one sql statement
  # Vote.where(votable: self).sum('case when up_vote then 1 else -1 end')
  def calculate_vote
    upvote = self.votes.where(up_vote:true).count
    downvote= self.votes.count - upvote
    net=upvote-downvote
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include QuestionsHelper

  def index
    mode = params[:query] || "latest"
    mode == "latest" ? @questions = Question.latest : @questions = Question.greatest
    # don't leave comments in master
    # @questions = Question.all
  end

  #Think about adding a before_action in the app controller to guard the mutating actions
  def new
    if logged_in?
      @question = Question.new
      render :'questions/new'
    else
      flash.alert = "You must be logged in to ask a question."
      redirect_to new_sessions_path
    end
  end

  def create
    @question = Question.new(question_params)


    if @question.save
      if params[:tag_names]
        tags = create_new_tags(params[:tag_names], @question)
      end
      redirect_to questions_path
    else
      @errors = @question.errors.full_messages
      render :'questions/new'
    end
  end

  def edit
    @question = Question.find_by(id: params[:id])
  end

  def update
    @question = Question.find_by(id: params[:id])
    @question.assign_attributes(question_params)
    if @question.save
      redirect_to question_path(@question)
    else
      @errors = @question.errors.full_messages
      render :'questions/edit'
    end
  end

  def show
    @question = Question.find_by(id: params[:id])
    #this query is implicit in @question.answers
    @answers = Answer.where(question_id: @question.id)
    @answers = @answers.sort_by{|answer| -answer.vote_count}
  end

  def destroy
    question = Question.find_by(id: params[:id])
    question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :body).merge(user_id: current_user.id)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper

  def separate_tags(tag_names)
    tag_names.split(", ")
  end

  #This looks like model logic for tag
  def create_new_tags(tag_names, question)
    separate_tags(tag_names).map do |tag_name|
      tag_name = tag_name.downcase
      tag = Tag.find_or_create_by(name: tag_name)
      tag.touch
      unless question.tags.include?(tag)
        question.tags << tag
      end
    end
  end

end

app/views/questions/_answer_body.html.erb
<div class="row">
  <div class="col-sm-1 answerVoteControl">
    <span class="glyphicon glyphicon-triangle-top" data-aid="<%=answer.id%>"></span>
    <p id="answerCount<%=answer.id%>"><%=answer.calculate_vote%></p>
    <span class="glyphicon glyphicon-triangle-bottom" data-aid="<%=answer.id%>"></span>
  </div>
  <div class="col-sm-11">
    <div class="row">
      <%= answer.body %> <% if current_user && answer.user_id == current_user.id %><%= link_to "Edit", edit_question_path(@question, answer) %> | <%= form_for [@question, answer], method: :delete, :html=>{:class=>'commentControl'} do |f| %><%= f.submit "Delete", class:"btn btn-link commentControl" %><% end %><% end %>
    </div>
    <div class="answerSecondRow row">
      <div class="questionOwnerControl col-sm-8">
          <%= render partial:"questions/comment_display", locals:{source:answer}%>
        <% if logged_in? %>
          <div class="row">
            <%= link_to "add a comment", new_answer_comment_path(answer) %>
          </div>
        <% end %>
      </div>

      <div class="col-sm-4">
        <p>answered: <%= answer.created_ago %> days ago</p>
        <%= link_to answer.user.username, user_path(answer.user) %>
      </div>
    </div>
  </div>
</div>

app/views/questions/_answer_form.html.erb
<%= form_for [question, answer] do |f| %>
    <div class="form-group">
      <%= f.text_area :body ,class:"form-control", rows:"5"%>
    </div>
    <div class="form-group formBottomGroup">
      <%= f.submit id: "create-answer-btn", class:"btn btn-primary btn-block" %>
    </div>
<% end %>

app/views/questions/_comment_display.html.erb
<% source.comments.each do |comment| %>
  <div class="row commentRow"><%= comment.body %> - <%= link_to comment.user.username, user_path(comment.user), class:"commentUser"%> <%=comment.created_at %> <% if current_user && comment.user_id == current_user.id %>
      <%= link_to "Edit", edit_question_comment_path(source, comment) %> | <%= form_for [source, comment], method: :delete, :html=>{:class=>'commentControl'} do |f| %><%= f.submit "Delete", class:"btn btn-link commentControl" %><% end %><% end %></div>
<% end %>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <div class="form-group">
    <label for="tag_names">Tags</label>
    <input type="text" name="tag_names" placeholder="e.g. Ruby, JavaScript" class="form-control">
  </div>
  <div class="from-group">
    <%= f.submit class:"btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div class="questionRow row">
  <div class="vote col-sm-2">
    <p><%= question.vote_count %></p>
    <p>votes</p>
  </div>
  <div class="answer col-sm-2">
    <p><%= question.answers.length%></p>
    <p>answers</p>
  </div>
  <div class="rowQuestionTag col-sm-8">
    <div class="question row">
      <%= link_to question.title, question_path(question) %>
    </div>
    <div class="tags row">
      <% question.tags.each do |tag| %>
        <span class="label label-info"><%= link_to tag.name, tag_path(tag) %></span>
      <% end %>
          <p class="questionCreatedTime">asked: <%= question.created_ago %> days ago <%= link_to question.user.username, user_path(question.user) %></p>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<h2>Edit question</h2>

<%= render "form" %>

app/views/questions/index.html.erb
<div class="tags">
	<span class="label label-info"><%= link_to "Latest", question: :index,:query => "latest"%></span>
	<span class="label label-info"><%= link_to "Greatest", question: :index, :query => "greatest" %></span>
</div>

<%= render @questions %>

app/views/questions/new.html.erb
<h2 style="text-align:center;">New Question</h2>
<%= render "form" %>

app/views/questions/show.html.erb
<h1 class="questionTitle row"><%= @question.title %></h1>
<div class="row">
  <div class="col-sm-1 questionVoteControl">
    <span class="glyphicon glyphicon-triangle-top" id="questionUpvoteButton" data-qid="<%=@question.id%>"></span>
    <p id="questionVote"><%=@question.calculate_vote%></p>
    <span class="glyphicon glyphicon-triangle-bottom" id="questionDownvoteButton" data-qid="<%=@question.id%>"></span>
  </div>
  <div class="col-sm-11">
    <div class="row questionBody">
      <p><%= @question.body %></p>
    </div>

    <div class="tags row questionTags">
      <% @question.tags.each do |tag| %>
        <span class="label label-info"><%= link_to tag.name, tag_path(tag)%></span>
      <% end %>
    </div>

    <div class="row questionControlRow">
      <div class="questionOwnerControl col-sm-8">
        <% if current_user && @question.user_id == current_user.id %>
          <div class="questionControlButtons row">
            <%= link_to "Edit", edit_question_path(@question), class:"btn btn-sm btn-default col-sm-1" %>
            <%= form_for @question, method: :delete do |f| %>
              <%= f.submit "Delete", class:"btn btn-sm btn-default col-sm-1"%>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="col-sm-4">
          <p class="questionOwner">asked: <%= @question.created_ago %> days ago by <%= link_to @question.user.username, user_path(@question.user) %></p>
      </div>
    </div>
    <div id="questionComments">
      <%=render partial:"comment_display",locals:{source:@question}%>
    </div>
    <%if current_user%>
      <div class="row addCommentButton" id="questionAddComment">
        <%= link_to "add a comment", new_question_comment_path(@question) %>
      </div>
    <%end%>
  </div>
</div>

<% if logged_in? %>
  <div class="row addCommentButton">
    <%= link_to "add a comment", new_question_comment_path(@question) %>
  </div>
<% end %>

<% if @question.answers.length == 0 %>
  <div class="row">
    <h2>There are no answers for this question yet</h2>
  </div>
<% else %>
  <div class="row">
    <h2><%=@question.answers.length%> Answers</h2>
  </div>
<% end %>

<div id="answerRow">
<% @answers.each do |answer| %>
<div class="row">
  <div class="col-sm-1 answerVoteControl">
    <span class="glyphicon glyphicon-triangle-top" data-aid="<%=answer.id%>"></span>
    <p id="answerCount<%=answer.id%>"><%=answer.calculate_vote%></p>
    <span class="glyphicon glyphicon-triangle-bottom" data-aid="<%=answer.id%>"></span>
  </div>
  <div class="col-sm-11">
    <div class="row answerFirstRow">
      <%= answer.body %> <%if current_user && (answer.user_id == current_user.id)%><%= link_to "Edit", edit_question_path(@question, answer) %> | <%= form_for [@question, answer], method: :delete, :html=>{:class=>'commentControl'} do |f| %><%= f.submit "Delete", class:"btn btn-link commentControl" %><% end %><% end %>
    </div>
    <div class="answerSecondRow row">
      <p><strong>Comments:</strong></p>
      <div class="questionOwnerControl col-sm-8">
        <div class="eachAnswerComments">
          <%= render partial:"comment_display", locals:{source:answer}%>
        </div>
        <% if logged_in? %>
          <div class="row answerComments">
            <%= link_to "add a comment", new_answer_comment_path(answer) %>
          </div>
        <%end%>
      </div>

      <div class="col-sm-4">
        <p>answered: <%= answer.created_ago %> days ago</p>
        <%= link_to answer.user.username, user_path(answer.user) %>
      </div>
    </div>
  </div>
</div>
<% end %>
</div>

<% if logged_in? %>
  <div class="row">
    <h2>Your Answer</h2>
    <%= render partial:"answer_form",locals:{question: @question,answer: Answer.new}%>
  </div>
<% end %>