config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'
  resources :users, only: [:show, :index, :new, :create]
  resource :sessions, only:[:new, :create, :destroy]
  resources :questions do
    resources :comments, except: [:show] do
    end
  end

  resources :questions do
    resources :answers
  end
  resources :answers, except: [:show] do
    resources :comments, except: [:show, :index] do
    end
  end

  resources :tags, only: [:show, :index]
  resources :questions, only:[] do
    resources :votes, only:[:create]
  end
  resources :answers, only:[] do
    resources :votes, only:[:create]
  end
  post '/tags/search' => 'tags#search'
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
	include Createable

  has_secure_password

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :username, length: {in: 1..40}

  def top_three_tags
  	occurances = occurance_hash(all_tags)
  	ordered_tags_hash = occurances.sort_by{|_key, value| -value}.to_h
    top_tags_objects = ordered_tags_hash.keys.shift(3)
    top_tags_objects.map(&:name)
  end

  def recent_three_questions
    questions.order(created_at: :DESC).limit(3)
  end

  def recent_three_answers
    answers.order(created_at: :DESC).limit(3)
  end

  def karma
    karma_array = self.questions.map(&:vote_count) + self.answers.map(&:vote_count)
    karma_array.reduce(:+)
  end

  private

  def all_tags
  	self.questions.map do |question|
  		question.tags
  	end.flatten
  end

  def occurance_hash(tags_array)
  	hash = Hash.new(0)
  	tags_array.each do |tag|
  		hash[tag] += 1
  	end
  	hash
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now.alert = "Your user information is not valid"
      render :new
    end

  end

  def index
    @counter=0;
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/views/users/index.html.erb
<h2>Users</h2>
<div class="row">
<% @users.each do |user| %>
		<div class="col-sm-4">
			<div class="thumbnail">
				<p><%= link_to user.username, user_path(user) %></p>
				<p>Karma: <%= user.karma %></p>
				<p>Hotest Tags:</p>
				<div class="tags row" style="padding-left:15px; padding-right:15px;">
					<% user.top_three_tags.each do |tag| %>
						<span class="label label-info"><%= link_to tag, tag_path(tag) %></span>
					<% end %>
				</div>
			</div>
		</div>
		<%@counter+=1%>
		<%if @counter%3==0%>
			</div>
			<div class="row">
		<%end%>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <fieldset>
    <div>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.submit 'Register' %>
    </div>
  </fieldset>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>
<p>Karma: <%= @user.karma %></p>
<p>Top tags: 
	<span class="tags"><% @user.top_three_tags.each do |tag| %>
	<span class="label label-info"><%= link_to tag, tag_path(tag) %></span>
	<% end %></span>
</p>
<p>	Member for: <%= @user.created_ago %> days</p>

<div id="user-question-container">
	<h3>Recent Questions:</h3>
	<% @user.recent_three_questions.each do |question| %>
		<div class="panel panel-primary">
			<div class="panel-heading">
		 		<h3 class="panel-title"><%= link_to question.title, question_path(question) %></h3>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-sm-6">
		 			<p><%= truncate(question.body, limit: 80) %></p>
		 			<p>asked: <%= question.created_ago %> days ago by <%= question.user.username %></p>
		 		</div>
		 		<div class="col-sm-6">
					<p>Votes: <%= question.vote_count %></p>
					<p>Answers: <%= question.answers.count %></p>
					<div class="tags row">
						<% question.tags.each do |tag| %>
							<span class="label label-info"><%= link_to tag.name, tag_path(tag) %></span>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<% end %>
</div>

<h3>Recent Answers:</h3>
<% @user.recent_three_answers.each do |answer| %>
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title"><%= link_to answer.question.title, question_answer_path(answer.question, answer)%></h3>
		</div>
		<div class="panel-body">
			<p><%= truncate(answer.body, limit: 80) %></p>
			<p>Votes: <%= answer.vote_count %></p>
			<p>Time: <%= answer.created_ago %> days ago</p>
		</div>
	</div>
<% end %>