config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'
  resources :users, only: [:show, :index, :new, :create]
  resource :sessions, only:[:new, :create, :destroy]
  resources :questions do
    resources :comments, except: [:show] do
    end
  end

  resources :questions do
    resources :answers
  end
  resources :answers, except: [:show] do
    resources :comments, except: [:show, :index] do
    end
  end

  resources :tags, only: [:show, :index]
  resources :questions, only:[] do
    resources :votes, only:[:create]
  end
  resources :answers, only:[] do
    resources :votes, only:[:create]
  end
  post '/tags/search' => 'tags#search'
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :questions

  validates :name, presence:true
  validates :name, length: {in: 1..30}

  def self.latest
    Tag.all.order(updated_at: :desc)
  end

  #Do this in a query
  def self.greatest
    tags = Tag.all
    tags = tags.sort_by{|tag| -tag.questions.count}
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    mode = params[:query] || "latest"
    mode == "latest" ? @tags = Tag.latest : @tags = Tag.greatest
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def search
    @tag = Tag.find_by(name: params[:search_name].downcase)
    if @tag
      render "tags/show"
    else
      redirect_to tags_path
    end
  end
end

app/views/tags/index.html.erb
<!-- TODO: Make this route work -->
<h2> #tags </h2>
<div id="search_by_tag">
  <%= form_tag tags_search_path do %>
    <%= text_field_tag :search_name %>
    <%= submit_tag "search by tag"%>
  <% end %>
</div>
<div id="latest_and_greatest">
  <%= link_to "latest", tags: :index, :query => "latest" %> <%= link_to "greatest", tags: :index, :query => "greatest" %>
</div>
<% @tags.each do |tag|%>
<%= link_to(raw("<h4 class='list-group-item-heading'><span class='tagName'>#{tag.name}</span><span class='badge' style='float:right;'>#{tag.questions.count}</span></h4><p class='list-group-item-text'>#{tag.questions.added_today.length} added today</p><p class='list-group-item-text'>#{tag.questions.added_this_week.length} added this week</p>"), tag_path(tag),{:class=>'list-group-item'})%>
<% end %>

app/views/tags/show.html.erb
<%= link_to "back to all tags", tags_path %>
<h2><%= @tag.name.upcase %></h2>  
<div>
  <ul>
    <% @tag.questions.each do |question|%>
      <li>
        <p> <%= question.vote_count %> votes, <%= question.answers.count %> answers </p>
        <p><%= link_to question.title, question_path(question) %></p>
        <p><%= truncate(question.body, limit: 80) %></p>
        <p class="list_of_tags"><% question.tags.each do |tag| %>
            <%= link_to tag.name, tag_path(tag) %>
           <% end %>
        </p>
      </li>
    <% end %>
  </ul>
</div>