config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'
  resources :users, only: [:show, :index, :new, :create]
  resource :sessions, only:[:new, :create, :destroy]
  resources :questions do
    resources :comments, except: [:show] do
    end
  end

  resources :questions do
    resources :answers
  end
  resources :answers, except: [:show] do
    resources :comments, except: [:show, :index] do
    end
  end

  resources :tags, only: [:show, :index]
  resources :questions, only:[] do
    resources :votes, only:[:create]
  end
  resources :answers, only:[] do
    resources :votes, only:[:create]
  end
  post '/tags/search' => 'tags#search'
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mmsz</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <li><%= link_to 'StackUnderFlow', root_path%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to current_user.username, user_path(current_user) %></li>
          <li><%= link_to 'Logout', logout_path %></li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
          <li><%= link_to 'Register', register_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  <div class="container">
    <div id="flash-messages">
      <% if flash.any?  %>
        <div id="flash">
          <% flash.each do |type, message| %>
            <div class="<%= type %>">
              <%= message %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div id="error-messages">
      <% if @errors %>
        <% @errors.each do |error| %>
          <p><%= error %></p>
        <% end %>
      <% end %>
    </div>
    <div class="row secondaryNav">
      <div id="logo" class="col-sm-4">
        <%= link_to "STACKUNDERFLOW", root_path, style:"text-decoration:none;" %>
      </div>
      <div class="optionLinksHome col-sm-8">
        <div class="optionLinksHomeRight">
        <span class="label label-default"><%= link_to "Ask a Question", new_question_path, style:"text-decoration:none;"%></span>
        <span class="label label-default"><%= link_to "Tags", tags_path, style:"text-decoration:none;"%></span>
        <span class="label label-default"><%= link_to "Users", users_path, style:"text-decoration:none;"%></span>
        </div>
      </div>
    </div>
    <%= yield %>
  </div>
</body>
</html>